### ISSUE TITLE
Raycast built-in plugin parity

### ISSUE THREAD

**Issue by Exidex** [project-gauntlet/gauntlet#15]
Here's a list of planned built-in plugins. Every single plugin here should be possible to implement with the same set of features available to all plugins but some of them may not be possible at the moment and require additional features that are documented at https://github.com/project-gauntlet/gauntlet/issues/13. Ideally all built-in plugins are available on all platforms but in some cases OS-specific functionality is desirable. Please comment for plugin idea that could be a good candidate for bundling with Gauntlet itself.

Plugin contributions are welcome

- [x] Applications
  - [ ] OS support
    - [x] Linux
    - [x] macOS
    - [ ] Windows  - https://github.com/project-gauntlet/gauntlet/issues/9
  - [x] Settings
    - [x] macOS 
  - [ ] Show running applications
    - [ ] Focus
    - [ ] Kill
- [x] Calculator
  - [x] Currency exchange rates 
- [ ] System
  - [ ] Hibernation
  - [ ] Sleep
  - [ ] Turn off
  - [ ] Logout
  - [ ] Restart
  - [ ] Change Volume
  - [ ] Wifi Settings
  - [ ] Bluetooth Settings
  - [ ] ...
- [ ] Processes management
  - [ ] Show memory and CPU usage
  - [ ] Kill
  - [ ] OS specific
    - [ ] Unix-like
      - [ ] Send specific signal to process
- [ ] Window management
  - [ ] Windows
  - [ ] macOS
- [ ] File Search
- [ ] Snippets
- [ ] Clipboard history
- [ ] Quick links
- [ ] Emoji Picker
